
GET http://127.0.0.1:8000/index       HTTP/1.1

####

POST http://127.0.0.1:8000/users/singin        HTTP/1.1
content-type: application/json

{
    "username": "str2",
    "email": "str23",
    "password": "str",
    "dni": 32
}

####

POST http://127.0.0.1:8000/users/login                  
Content-Type: application/json

{
  "email": "str23",
  "password": "str"
}

####
POST http://127.0.0.1:8000/users/deleteUser                 
Content-Type: application/json

{
    "id": 4
}

####
GET http://127.0.0.1:8000/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdHIyMyIsImV4cCI6MTczMTA0NzcxNH0.qciy32vAthWycp3VcAPO82OeRCmD475Ov07NGinXODA
